import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import styles from '../styles/Home.module.css'
import requests from '../utils/requests'

export default function Home({results}) {
  console.log(results)
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1>Let's build hulu 2.0</h1> */}

      {/* header */}

      <Header />
      {/* nav */}
      <Nav />
      {/* results */}
      <Results
        results ={results}
      />
    </div>
  )
}


//fetching data from server
export async function getServerSideProps(context) {
  //fetching data from url
  const genre = context.query.genre;
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url ||
    requests.fetchTrending.url}`).then((res) => res.json())

    console.log(`my request ${request.results}`)

    console.log(`my request ${request}`)
  return {
    props: {
      results: request.results,
    }
  }

}
